[workspace]
members = [
    "node",
    "primitives",
    "runtime",
    "zrml/authorized",
    "zrml/court",
    "zrml/liquidity-mining",
    "zrml/market-commons",
    "zrml/orderbook-v1",
    "zrml/orderbook-v1/fuzz",
    "zrml/prediction-markets",
    "zrml/prediction-markets/fuzz",
    "zrml/prediction-markets/runtime-api",
    "zrml/rikiddo",
    "zrml/rikiddo/fuzz",
    "zrml/simple-disputes",
    "zrml/swaps",
    "zrml/swaps/fuzz",
    "zrml/swaps/rpc",
    "zrml/swaps/runtime-api",
]
resolver = "2"

[patch."https://github.com/purestake/open-runtime-module-library"]
orml-benchmarking = { git = "https://github.com/zeitgeistpm/open-runtime-module-library", branch = "slashed-0.9.17-2" }
orml-currencies = { git = "https://github.com/zeitgeistpm/open-runtime-module-library", branch = "slashed-0.9.17-2" }
orml-tokens = { git = "https://github.com/zeitgeistpm/open-runtime-module-library", branch = "slashed-0.9.17-2" }
orml-traits = { git = "https://github.com/zeitgeistpm/open-runtime-module-library", branch = "slashed-0.9.17-2" }
