[[bin]]
doc = false
name = "pool_creation"
path = "pool_creation.rs"
test = false

[[bin]]
doc = false
name = "general_pool_joining"
path = "general_pool_joining.rs"
test = false

[[bin]]
doc = false
name = "exact_amount_pool_joining"
path = "exact_amount_pool_joining.rs"
test = false

[[bin]]
doc = false
name = "exact_asset_amount_pool_joining"
path = "exact_asset_amount_pool_joining.rs"
test = false

[[bin]]
doc = false
name = "input_swap_exact_amount_pool_joining"
path = "input_swap_exact_amount_pool_joining.rs"
test = false

[[bin]]
doc = false
name = "output_swap_exact_amount_pool_joining"
path = "output_swap_exact_amount_pool_joining.rs"
test = false

[[bin]]
doc = false
name = "exact_asset_amount_pool_exiting"
path = "exact_asset_amount_pool_exiting.rs"
test = false

[[bin]]
doc = false
name = "exact_amount_pool_exiting"
path = "exact_amount_pool_exiting.rs"
test = false

[[bin]]
doc = false
name = "general_pool_exiting"
path = "general_pool_exiting.rs"
test = false

[dependencies]
arbitrary = { features = ["derive"], version = "1.0" }
libfuzzer-sys = "0.4"
zrml-swaps = { features = ["mock"], path = ".." }
zeitgeist-primitives = { path = "../../../primitives" }
sp-runtime = { branch = "moonbeam-polkadot-v0.9.17", default-features = false, git = "https://github.com/purestake/substrate" }
frame-support = { branch = "moonbeam-polkadot-v0.9.17", default-features = false, git = "https://github.com/purestake/substrate" }
rand = "0.8.4"
orml-traits = { branch = "moonbeam-polkadot-v0.9.17", default-features = false, git = "https://github.com/PureStake/open-runtime-module-library" }

[package]
authors = ["Automatically generated"]
edition = "2021"
name = "zrml-swaps-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true
