name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  balance_to_fixedu_conversion_MAYHEMFILE: balance_to_fixedu_conversion .mayhemfile 
  ema_market_volume_first_state_MAYHEMFILE: ema_market_volume_first_state.mayhemfile 
  ema_market_volume_second_state_MAYHEMFILE: ema_market_volume_second_state.mayhemfile 
  ema_market_volume_third_state_MAYHEMFILE: ema_market_volume_third_state.mayhemfile 
  fee_sigmoid_MAYHEMFILE: fee_sigmoid.mayhemfile 
  fixedi_to_fixedu_conversion_MAYHEMFILE: fixedi_to_fixedu_conversion.mayhemfile 
  fixedu_to_balance_conversion_MAYHEMFILE: fixedu_to_balance_conversion.mayhemfile 
  fixedu_to_fixedi_conversion_MAYHEMFILE: fixedu_to_fixedi_conversion.mayhemfile 
  rikiddo_pallet_MAYHEMFILE: rikiddo_pallet.mayhemfile 
  rikiddo_with_calculated_fee_MAYHEMFILE: rikiddo_with_calculated_fee.mayhemfile 
  rikiddo_with_initial_fee_MAYHEMFILE: rikiddo_with_initial_fee.mayhemfile 

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
	  file: Dockerfile_fuzz

      - name: Start analysis
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }}
          sarif-output: sarif

      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif
